### ISSUE TITLE
Product Title in Templates/Products/Teaser.html

### ISSUE THREAD

**Issue by taunusweb** [extcode/cart#102]
I found the variable `{cartProduct.title}` in the above mentioned template, in my opinion it should be
`{product.title}`, am I right?

**Comment by extcode** [comment]
You are right. I'll fix this as soon as possible (today).

**Comment by taunusweb** [comment]
I use my own template, so don't hurry...

**Comment by extcode** [comment]
Solved with version 3.4.1.
