### ISSUE TITLE
Image in 'ProductList.html'

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#11]
I try to add a product image to the file 'ProductList.html'. 
My problem: the variable 
`{product.firstImage.originalResource.originalFile.uid}`
remains empty. What do I miss?

Thanks for your help!
Hobokens

**Comment by Hobokens** [comment]
Hi Daniel,

After a while I try again to solve the above problem without success. It would be great to get a hint from you.

Regards and thanks for your help!
Hobokens

**Comment by izzycole** [comment]
Hi Daniel,

it would be nice if the Cart\Product would provide the original Product\Product as a property, e.g. for displaying images or other product info in the cart view.

Thanks for the great extension!
Sebi

**Comment by rintisch** [comment]
How this can be solved is shown in the documentation of EXT:cart_products: https://docs.typo3.org/p/extcode/cart-products/5.0/en-us/Tutorials/ImagesInCart/Index.html
