### ISSUE TITLE
special price shown first page load, but no special price defined

### ISSUE THREAD

**Issue by matin73** [extcode/cart#118]
i have a strange behaviour. i have installed latest cart version on 8.7.3 with introduction package. i have 2 products - 1 simple and 1 configurable product. for testing i set price on config product to 12.00 and 2 backend variants to 19,00 and 99,00.

if i clear all caches (also system caches) in typo3 and load list of products there is a special price shown, but i have not configured any special price (s. screenshot) - price and special price are 12.00 from config-product. if i reload page (from cache) the right price of cheapest variant (€ 19,00) is shown (s. screenshot 2)!?
![grafik](https://user-images.githubusercontent.com/3177275/27987324-266fdfa4-640c-11e7-900b-ef984d6fbbc5.png)
![grafik](https://user-images.githubusercontent.com/3177275/27987325-30eea05a-640c-11e7-8720-d3fe95f047d1.png)
![grafik](https://user-images.githubusercontent.com/3177275/27987336-68d5c430-640c-11e7-8b04-236711ea807a.png)
![grafik](https://user-images.githubusercontent.com/3177275/27987347-8d53f9d0-640c-11e7-8c51-05c61cd7e818.png)

**Comment by matin73** [comment]
... wrong special price also shown on list page on cached pages ... so it seems a bug with configurable products.

**Comment by rintisch** [comment]
@matin73 
This is a really delayed response: Does the problem still occur? Otherwise I would close this issue due to its age.

**Comment by rintisch** [comment]
I will close this ticket due to missing feedback. You're off course still welcome to respond!
