### ISSUE TITLE
Wrong access check in Order showAction

### ISSUE THREAD

**Issue by martinlipp** [extcode/cart#142]
The access check for frontend users of the showAction in the OrderController is faulty: it compares the uid of the logged in user with the FrontendUser object of Order\Item and therefore fails even with the correctly logged in user.
See: https://github.com/extcode/cart/blob/e89613f5424b333e9b919d7d6829a1d7527d856e/Classes/Controller/OrderController.php#L294

Correct would be:
`if ($orderItem->getFeUser()->getUid() !== $feUser) {`

**Comment by extcode** [comment]
Solved with version 4.2.2.
Solved with version 3.12.9.
