### ISSUE TITLE
This can't work and makes no sense

### ISSUE THREAD

**Issue by gerchomat** [extcode/cart#143]
https://github.com/extcode/cart/blob/e89613f5424b333e9b919d7d6829a1d7527d856e/Classes/Domain/Repository/Product/ProductRepository.php#L75-L91

**Comment by extcode** [comment]
This is an old not used function I forgot to remove. Will remove this method as soon as possible. Thank you.

**Comment by extcode** [comment]
Solved with version 4.2.3.
Solved with version 3.12.10.
