### ISSUE TITLE
Improve tt_content rendering

### ISSUE THREAD

**Issue by siwa-pparzer** [extcode/cart#146]
The tt_content rendering doesn't work quite well with custom content elements.

In the Product/Show.html Template ~ 55 you use:
`<f:cObject typoscriptObjectPath="tt_content.{content.contentType}.20"
                           data="<cart:mapModelPropertiesToTableColumns class='Extcode\\Product\\Domain\\Model\\TtContent' table='tt_content' data='{content}' />"/>`

I would recommend following replacement:
`<f:cObject typoscriptObjectPath="lib.renderContent" data="{content.uid}" />`

and following TS in the setup.txt:

_lib.renderContent = RECORDS
lib.renderContent {
    source.current = 1
    tables = tt_content
    dontCheckPid = 1
    conf.tt_content =< tt_content
}_

**Comment by extcode** [comment]
I'll add some tests and than add this to 4.x and 5.x.pre.

**Comment by rintisch** [comment]
I will close this issue due to its age.
