### ISSUE TITLE
The argument “additionalAttributes” was registered with type “array”, but is of type “string” in view helper “TYPO3\CMS\Fluid\ViewHelpers\Form\CheckboxViewHelper”

### ISSUE THREAD

**Issue by basvandertogt** [extcode/cart#148]
I’m facing this error: #1237900529: The argument “additionalAttributes” was registered with type “array”, but is of type “string” in view helper “TYPO3\CMS\Fluid\ViewHelpers\Form\CheckboxViewHelper” It looks like this has something todo with this viewhelper: <f:form.checkbox name=“shipping_same_as_billing”
                                         id=“shipping_same_as_billing”
                                         value=“{f:if(condition:‘{cart.shippingCountry}‘,then:‘false’,else:‘true’)}”
                                         title=“{f:translate(key:‘tx_cart.same_address’)}”
                                         additionalAttributes=“{f:if(condition:‘{cart.shippingCountry} == \‘\’‘, then: ‘{checked: \‘checked\‘}’)}“/>

I fixed this by:

<f:form.checkbox name=“shipping_same_as_billing”
                                         id=“shipping_same_as_billing”
                                         value=“{f:if(condition:‘{cart.shippingCountry}‘,then:‘false’,else:‘true’)}”
                                         title=“{f:translate(key:‘tx_cart.same_address’)}”
                                         additionalAttributes="{f:if(condition: cart.shippingCountry, else: '{checked: \'checked\'}')}"/>

**Comment by matin73** [comment]
thanks! worked also for me

**Comment by matin73** [comment]
<f:form.checkbox name="shipping_same_as_billing"
											id="shipping_same_as_billing"
											value="{f:if(condition:'{cart.shippingCountry}',then:'false',else:'true')}"
											title="{f:translate(key:'tx_cart.same_address')}"
											additionalAttributes="{f:if(condition: cart.shippingCountry, else: '{checked: checked}')}"/>

seems correct
