### ISSUE TITLE
special price not working correct - render() only called once

### ISSUE THREAD

**Issue by matin73** [extcode/cart#159]
If you ad special price to product, the special price is only shown once if you clear system cache. if you reload page no special price is shown. I think problem is, that render() is only called once as described here: https://stackoverflow.com/questions/34729014/typo3-ver-7-6-2-condition-viewhelpers-evaluated-only-once/
![unbenannt-2](https://user-images.githubusercontent.com/3177275/31851333-1b525a16-b664-11e7-8685-81370ff4d84f.jpg)

I think something like this can solve this problem:

 public function render()
    {
        return static::renderStatic(
            [],
            $this->renderChildrenClosure,
            $this->renderingContext
        );
    }

    public static function renderStatic( ....public static function renderStatic(
        array $arguments,
        \Closure $renderChildrenClosure,
        RenderingContextInterface $renderingContext
    ) {
.....

**Comment by extcode** [comment]
/**
     * @param array|NULL $arguments
     * @return boolean
     * @api
     */
    protected static function evaluateCondition($arguments = null)
    {
        $product = $arguments['product'];
        $bestSpecialPrice = $product->getBestSpecialPrice(self::getFrontendUserGroupIds());
        return $bestSpecialPrice < $product->getMinPrice();
    }

**Comment by extcode** [comment]
Solved with version 4.7.3.
Solved with version 5.0.0.
