### ISSUE TITLE
Settings 'showCartAction' depending on Country

### ISSUE THREAD

**Issue by siwa-pparzer** [extcode/cart#167]
It would be nice if the following TS Settings could be set individual for each country:
plugin.tx_cart.settings.showCartAction

**Comment by rintisch** [comment]
@siwa-pparzer 
I do not really get the intention. But I guess due to the ticket's date this is not relevant any longer and can be closed?

**Comment by rintisch** [comment]
I will close this ticket due to missing feedback. You're off course still welcome to respond!
