### ISSUE TITLE
Clarify generic attachments for buyer/seller mails

### ISSUE THREAD

**Issue by ghost** [extcode/cart#175]
Heya,

I got a question regarding the mail attachments. Currently the mailer service and order controller seem to handle pdf only. Despite the getter named getSellerPdf or getBuyerPdf the mailer service seems to be capable of attaching any type of file to the swift mail message.

For instance, it would be nice if the seller could get an order in his prefered format for the system they are using for handling orders (e.g csv, xml)

Let me now, if I can help with a pull request, or of something is already in the works.

cheers
Jonathan

**Comment by rintisch** [comment]
I will close this ticket as this can be solved with the newly introduced `AttachmentEvent` (see https://github.com/extcode/cart/pull/469/commits/f6cd388c9aa99478586700c1cfa814446b8ad980)
