### ISSUE TITLE
check stock when product should be added to cart or number should be updated

### ISSUE THREAD

**Issue by ashupatel1990** [extcode/cart#179]
No stock handling on the product in backend, i can still add products to cart which has stock value 0. or do i miss anything, please kindly let me know.

**Comment by extcode** [comment]
I'll check this.

**Comment by extcode** [comment]
Solved with version 4.7.8.
Solved with version 5.0.0.

**Comment by ashupatel1990** [comment]
Thanks for your update.
I will update extension version.
