### ISSUE TITLE
Feature Request: calculate shipping cost by weight

### ISSUE THREAD

**Issue by TheMassassian** [extcode/cart#183]
Hi,

as of now it is not possible to calculate the shipping costs by the weight of the products in the cart.
I like to see this as a feature in the future.

Best Regards,

Yasin

**Comment by extcode** [comment]
I'm so sorry for the late answer. This is possible for a while, but wasn't documented. I add some documentation. You can add the weight of a product to service attribute 1 and use the `by_service_attribute_1_sum` condition. Have a closer look to the [Flex Price](https://docs.typo3.org/p/extcode/cart/6.7/en-us/AdministratorManual/Configuration/ShippingMethods/FlexPrices/Index.html) documentation.
