### ISSUE TITLE
Stock handling multi language

### ISSUE THREAD

**Issue by paul-keller** [extcode/cart#184]
In a multi language set up there is a problem with the stock handling of an item. The item is allways the same in all the languages. Translation works fine. But if we activate stock handling and then make an order in the front end in one language, the number of items on stock is only changed in the specific language. But it allways should be the same for all languages of course.

**Comment by kuprienko** [comment]
I've got a hint via Slack from Daniel and have a temporary fix for this: adding ‘l10n_display’ => ‘defaultAsReadonly’, to ‘stock’ in TCA > tx_cartproducts_domain_model_product_product.php seems to work
Official Bugfix will follow, he said.

However maybe it could be useful to consider the case where it makes sense to separate the stock handling for different languages.

**Comment by extcode** [comment]
I will try to enable the language specific warehouse management through a configuration. The standard should be language independent.

**Comment by extcode** [comment]
This was resolved with [Issue \#46](https://github.com/extcode/cart_products/issues/46) of cart_products.
