### ISSUE TITLE
Ke Search Indexer not working

### ISSUE THREAD

**Issue by MarcKoester** [extcode/cart#185]
The Ke_search_indexer is not working.
The SQL Statement in the ProductRepository seems to be wrong:

https://github.com/extcode/cart/blob/ae99a18e8c0fdec4d31b708c4a104d4fb482c1d2/Classes/Domain/Repository/Product/ProductRepository.php#L100-L113

What works for me:

```
SELECT tx_cart_domain_model_product_product.*, sys_category.cart_product_single_pid
FROM tx_cart_domain_model_product_product´
LEFT JOIN sys_category_record_mm
    ON sys_category_record_mm.uid_foreign = tx_cart_domain_model_product_product.uid
...
```

**Comment by rintisch** [comment]
@MarcKoester 
As this is totally outdated I will close this issue. Thanks for your contribution :)
