### ISSUE TITLE
Order status can't be updated, when shipping to the same address.

### ISSUE THREAD

**Issue by MarcKoester** [extcode/cart#190]
When making an order with checkbox `shipping_same_as_billing` active, the database field `tx_cart_domain_model_order_shipping.service_country` is set to an empty string.

When changing the status of this order in the Backend you get an an error:
`An error occurred while trying to call Extcode\Cart\Controller\OrderController->updateShippingAction()`
It is a validation error, because `shipping.serviceCountry` is empty, which is validated as `@validate NotEmpty`.

**Comment by discotizer** [comment]
Same here, waiting for a fix :)

**Comment by discotizer** [comment]
@extcode For me, i have the problem with typo3 7.6.30 and cart 4.8.0

**Comment by Hobokens** [comment]
The bugfix solved the problem for me. Thanks!

**Comment by discotizer** [comment]
Good to see but i switched previously to Shopware.
