### ISSUE TITLE
teaser plugin, addToCartByAjax will not work 

### ISSUE THREAD

**Issue by stephangrass** [extcode/cart#194]
addToCartByAjax will not work in teaser pugins, if more than one article is shown per page.
In cart.js the action ist called by $("#add-product-form").submit(function(e) { ... } and in  CatForm.html the add-to-cart form is inserted with <f:form pageUid="{pid}" id="add-product-form" ...

Changing id to class will work.

**Comment by extcode** [comment]
I'll fix this asap.

**Comment by stephangrass** [comment]
Any idea when you can fix it?

**Comment by Hobokens** [comment]
I have the teaser problem with cart 6.x

**Comment by rintisch** [comment]
The teaser plugin does no longer exists so I will close this ticket.
