### ISSUE TITLE
teaser plugin localisation

### ISSUE THREAD

**Issue by stephangrass** [extcode/cart#195]
localized products will not shown in teaser view.

I think you must change in the repository-function findByUids:

        $query->matching(
            $query->in('uid', $uids)
        );

by something like (I don't know, if this is the best way, but it works):

        foreach ($uids as $key => $value) {
            $constraints[] = $query->equals('uid', intval($value));
            $constraints[] = $query->equals('l10n_parent', intval($value));
        }
        $query->getQuerySettings()->setRespectSysLanguage(TRUE);
        $query->matching(
            $query->logicalAnd(
                $query->logicalOr(
                    $constraints
                )
            )
        );

**Comment by stephangrass** [comment]
Can you reproduce this issue?
Any idea when you can fix it?

**Comment by rintisch** [comment]
The teaser plugin does no longer exist so I will close this ticket
