### ISSUE TITLE
[FEATURE] Allow mails to be sent by queue via a scheduler task

### ISSUE THREAD

**Issue by AndreasA** [extcode/cart#210]
It would be nice if it were possible (optional) to sent mails via a queue / scheduler task.
That way if there is an issue during the original mail sent, e.g. SMTP server not reachable, they could be resent at a later date. 
Of course, the mails should only be sent if they are not too old, e.g. not older than 2 days or so (should be configurable) to avoid sending too old mails.

**Comment by rintisch** [comment]
@AndreasA 
This is a quite late reply but:
What you might want is spooling https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Mail/Index.html#mail-spooling or with TYPO3 v12 (as I understand it) the message bus (https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/MessageBus/Index.html#message-bus-1).

As these are possible solutions for your demand I will close this ticket.
