### ISSUE TITLE
Flexform Cart Plugin

### ISSUE THREAD

**Issue by patriceckhart** [extcode/cart#224]
## Bug Report

**Current Behavior**
In the Flexform of the plugin Cart, the fields for the e-mail addresses are not visible.

**Environment**
- TYPO3 version(s): 8.7.19
- cart version: 5.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Comment by extcode** [comment]
Can't confirm this. Can you provide a screenshot and the dump of the database row of the plugin?
I created a new instance, add a page for cart and the plugin (cart_cart) for the cart.

**Comment by patriceckhart** [comment]
<img width="1385" alt="bildschirmfoto 2019-01-03 um 14 12 30" src="https://user-images.githubusercontent.com/10776002/50639403-a66e4680-0f61-11e9-9665-7b75e9eb4884.png">
I integrated it into an existing instance.
