### ISSUE TITLE
no Cart

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#233]
## Bug Report

**Current Behavior**
When calling cart from detail view or by link I get the following error message instead of the cart

`The default controller for extension "Cart" and plugin "Cart" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.  `

**Environment**
- TYPO3 version(s): 9.5.3
- cart version: newest version from github (21.01.2019)
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS:  Windows 10

**Comment by extcode** [comment]
I can't comprehend that. Can you give me some more information? Which link in detail view you mean?

**Comment by Hobokens** [comment]
I'm talking about the button 'go to checkout'.

**Comment by extcode** [comment]
Hi, I have no Windows OS to test it. Can you contact me on Slack?
Otherwise I need more information. Do you use the cart_product extension?
Which link is called on the "go to checkout" button?

The button "go to checkout" is located in the CartPreview Plugin. And only redirects to the configured cart page id.

**Comment by nannione** [comment]
Same error here. I use the the cart_product extension. I also see two content elements when i select the cart plug-in (s. attachment) 
![Bildschirmfoto 2019-03-11 um 18 05 26](https://user-images.githubusercontent.com/7661543/54146688-6e372880-4428-11e9-9c08-3fea9d8814c2.png)

**Comment by Hobokens** [comment]
Hi Daniel,
sorry for my late reaction. I found the error  for myself. It was a wrong order pid. :-(
Thanks for your great extension.

Hobokens
