### ISSUE TITLE
cart.js references missing "showToTopLink" function

### ISSUE THREAD

**Issue by faktor-noack** [extcode/cart#237]
This patch: https://github.com/extcode/cart/commit/0a0e3b66e3216b185de5652c7927a95f765da162 introduced some javascript in the cart.js file that references a "showToTopLink" global function; however, none of the sourcecode refers to that, and thus the browser's Error Console will show it as missing.

**Comment by extcode** [comment]
I noticed that already. Currently I refactoring the whole JavaScript and split it up to some modules.
I hope I can merge the rewritten JavaScript code it in next release.
