### ISSUE TITLE
ShippingAddress not working (? value is not considered in controller)

### ISSUE THREAD

**Issue by chvonrohr** [extcode/cart#254]
## Bug Report

I implemented the cart module in the website. As in the module, I'd like to have the option to have a separate shipping address.

BUT, for me it's not working and checking the code, I can't imagine it could work..
In the Cart\OrderController, the field `shipping_same_as_billing` is not mapped and therefore not updating the cart-session once restored.
see: https://github.com/extcode/cart/blob/master/Classes/Controller/Cart/OrderController.php#L115

I fixed it, adding the field to the method params and setting the value to the cart:
```php
public function createAction(
        \Extcode\Cart\Domain\Model\Order\Item $orderItem = null,
        \Extcode\Cart\Domain\Model\Order\BillingAddress $billingAddress = null,
        \Extcode\Cart\Domain\Model\Order\ShippingAddress $shippingAddress = null,
        $shipping_same_as_billing = true  //FIX
    ) {
    // ...

    $orderItem->setBillingAddress($billingAddress); // after this existing code

    $this->cart->setShippingSameAsBilling($shipping_same_as_billing); // fix
    
    // ....
}
```

Then I adjusted the validation in the `initializeCreateAction` method:
````
$needShippingAddress = ($this->arguments->hasArgument('shipping_same_as_billing') && !$this->arguments->getArgument('shipping_same_as_billing'));// FRONTAL FIX
if ($argumentName == 'shippingAddress' && !$needShippingAddress) {
     continue;
}
````
After this, it almost worked. The `Cart::setShippingSameAsBilling()` threw an exception due too a wrong return type. So I had additionally to remove the `: void` return type.

```
Uncaught TYPO3 Exception
Return value of Extcode\Cart\Domain\Model\Cart\Cart::setShippingSameAsBilling() must be an instance of Extcode\Cart\Domain\Model\Cart\void, none returned?
```

**Current Behavior**
Ignores shipping address

**Expected behavior/output**
Shipping address?

**Environment**
- TYPO3 version(s): 8.7.27
- cart version: 5.5 (latest possible for TYPO3 v8)
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: debian

**Possible Solution**
see above

**Comment by chvonrohr** [comment]
meanwhile, I guess this is meant to be updated before (in the cart). as we are not dependent on refreshing shipping or payment options, it would be nice to work without refreshing the cart and send it directly to the order creation. (so rather feature?)

**Comment by extcode** [comment]
I can't reproduce that. The input field is not saved. It is only there to show the area for the shipping address. If data was entered there, a corresponding data record should also be saved in the order. The order then contains both a billing address and a shipping address. Otherwise only the invoice address will be saved.

**Comment by extcode** [comment]
Can you contact me on TYPO3 Slack? We can have a call and you can show me the behavior in your installation.

**Comment by extcode** [comment]
I think this is related to #250. Can you checkout and test cart v5.5.1?
