### ISSUE TITLE
error 'You have to specify a valid $taxClass for constructor.'

### ISSUE THREAD

**Issue by ralphbecker** [extcode/cart#255]
Hello,
I have two test servers, on the first the extension works fine, on the second the error
'# 1413999140 InvalidArgumentException You must specify a valid $ taxClass for the constructor.' is thrown when i add a product to the cart.
For the products i use the extension cart_product.
On both servers Typo3 9.5.3 and PHP7.2

I think that's a mistake in the environment, but I do not know where to find it.

Thank you in advance

**Comment by ralphbecker** [comment]
After a complete reinstallation of Typo and Cart the error did not occur anymore.

**Comment by Idleworks** [comment]
I stumbled upon this error too and fixed it whit this line in Typoscript:

`plugin.tx_cartproducts.settings.format.currency < plugin.tx_cart.settings.format.currency`
