### ISSUE TITLE
ext_typoscript_constants.typoscript with Site-Package

### ISSUE THREAD

**Issue by joeschi** [extcode/cart#262]
ext_typoscript_constants.typoscript is overriding custom Constants-Settings using Cart inside of an Site-Package, because the default Typoscript from extensions in the templatte-hierarchy is loaded after my static template of the site-package. I was wondering why the cart.pid has the value "0".

**Comment by stoppeye** [comment]
Same here. I think you should get rid of ext_typoscript_constants.typoscript + ext_typoscript_setup.typoscript altogether, as their use is discouraged in the [official documentation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html#ext-typoscript-constants-typoscript).

I you need some sensible defaults, why not put them into Configuration/TypoScript/constants.typoscript in the first place?

**Comment by stoppeye** [comment]
This problem seems fixed as of version 7. As far as I'm concerned, this issue can be closed.

**Comment by extcode** [comment]
Yes, I removed these files in v7.0.0/v7.0.1 and copy necessary configurations to setup.typoscript and constants.typoscript.
