### ISSUE TITLE
Adding products to cart via AJAX does not work when using a PageType RouteEnhancer

### ISSUE THREAD

**Issue by benwalch** [extcode/cart#263]
## Bug Report

**Current Behavior**
Adding items to cart does not work. The response of the Ajax request when adding a product to cart is not JSON, the whole html page is returned. This behaviour can be reproduced when having a RouteEnhancer of the type `PageType` configured in your site config, which maps the `type` parameter in URLs: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Feature-86160-PageTypeEnhancerForMappingTypeParameter.html

**Expected behavior/output**
Adding a product to cart works correctly using AJAX and with a `PageType` RouteEnhancer.

**Environment**
- TYPO3 version(s): 9.5.x
- cart version: 6.5.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux, Debian 10, Apache, PHP 7.2

**Possible Solution**
The issue is because of the lookup for a `type` parameter in the `$_GET` variable [here](https://github.com/extcode/cart/blob/02043f1bf5801fa2313bfe61f1d989e14fc949c6/Classes/Controller/Cart/ProductController.php#L118) and [here](https://github.com/extcode/cart/blob/02043f1bf5801fa2313bfe61f1d989e14fc949c6/Classes/Controller/Cart/ProductController.php#L154) in `ProductController->addAction`. This lookup for the `type` parameter may also occur at other places. When using a `PageType` Route Enhancer, there is no `type` parameter in the URL anymore, since it gets mapped to a suffix (e.g. '.html' or '.json', etc ..)

TYPO3 9 provides an [API](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/AccessingSiteConfiguration.html#accessing-the-current-site-object) for getting the current page type of the request. Using this API to determine if the request is made via the AJAX pageType or is a 'normal' request would be the better way in TYPO3 9 projects, as well as more bulletproof:

use
```
$pageType = $GLOBALS['TYPO3_REQUEST']->getAttribute('routing')->getPageType();
if ($pageType == $this->settings['addToCartByAjax']) {
    // deliver json
}
```
instead of
```
if (isset($_GET['type'])) {
```

**Comment by extcode** [comment]
Thank you for suggesting a solution. Instead of using `$this->settings['addToCartByAjax']` I use a constant. I'll make this configurable later. But for compatibility reasons I have to use this fix number, because they are fix in template too. The AJAX request works in EXT:cart 6.x for changing payments, shippings and currency without the setting `addToCartByAjax`. The type is fix in default templates.
I can change this in next major release.
