### ISSUE TITLE
Order List

### ISSUE THREAD

**Issue by hweckhardt** [extcode/cart#269]
## Bug Report

**Current Behavior**
Order list in frontend. Following error message:

Sorry, the requested view was not found.
The technical reason is: No template was found. View could not be resolved for action "list" in class "Extcode\Cart\Controller\Order\OrderController".

**Environment**
- TYPO3 version(s): [9.5.13]
- cart version: [6.6.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [ no]

**Comment by hweckhardt** [comment]
This was not a bug. The pathname was not complete. After extending the pathname to Resources/Templates/Cart/Order the template is found and the order list displayed. I close this issue.

**Comment by extcode** [comment]
I'll fix this by moving the templates to correct folder.
