### ISSUE TITLE
Combine coupon codes with fixed and percentage values

### ISSUE THREAD

**Issue by DTM-TYPO3** [extcode/cart#276]
I´d like to combine the fixed coupon values with percantage values for my cart-shop.
Is such a feature in progress? How long do you think would it take to implement such a feature in cart? 
Last year we had contact via email. Now I push a request in here - also for other users who are looking forward to such a feature :-)

Kind Regards
Stefanie Beutlich

**Comment by extcode** [comment]
Hello, this is currently not planned. The combination of percentage and fixed discounts is not easy to achieve.
From my point of view, this is only possible if the discount functionality is outsourced to an interface, EXT:cart comes with an implementation of this interface, but the calculation of discounts can be adapted to customer needs by own implementations.
Currently there is no project in which I would have to implement this feature and the free time I currently spend on documentation, stability and preparations for TYPO3 v10.

**Comment by extcode** [comment]
I had already written an estimate of the effort in my e-mail from early January.
