### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by taunusweb** [extcode/cart#28]
Hi,
there are some constants in the setup.txt, that don't have a counterpart in the constants.txt, e.g.
{$plugin.tx_cart.settings.cart.pid}
{$plugin.tx_cart.settings.cart.isNetCart}
{$plugin.tx_cart.settings.order.pid}

**Comment by rintisch** [comment]
I guess those constants are not defined with intention. It makes no sense to predefine PIDs as constants because it is project specific. 
The new documentation coming with version 9 describes how to handle this.

@extcode I think this could be closed.
