### ISSUE TITLE
Error in german translation for VAT (Umstatzsteuer)

### ISSUE THREAD

**Issue by rintisch** [extcode/cart#280]
## Bug Report

Two translations in german have mistakes, it's _Umstatzsteuer_ (there is one t too many)  instead of _Umsatzsteuer_.

**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 8.7
- cart version: seems to be in all of them (at least in 5 and 6)
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: *

**Possible Solution**
in `cart/Resources/Private/Language/de.locallang.xlf` > `tx_cart.tax_vat` and `tx_cart.tax_vat.value` have to be translated correctly.

**Comment by extcode** [comment]
I fixed it in the translation files. I will tag it as soon as possible.
