### ISSUE TITLE
Backend variant attribute is not available in a product (TYPO3 v9.5.18)

### ISSUE THREAD

**Issue by wtdesign** [extcode/cart#293]
It's not possible to use a "Backend variant attribute" in a product. You only can add them by list-view, but you can't add those, which I created before to a product.
Is there another extension which is necessary?

In the following documentation it's possible to do that, what I want. But it's for **tx_cart 4.8**. I use **tx_cart 6.8.2**
https://docs.typo3.org/p/extcode/cart/4.8/en-us/EditorManual/Records/Products/Variants/BackendVariants/Index.html

**Comment by extcode** [comment]
You do not need another extension for backend variants. But I don't understand your problem. At what point do you get into trouble? Where do errors occur?
Do you have the same problems with current version 6.9.0?
Can you give me some more information?

PS: I know, the documentation is a little bit outdated. Perhaps you have to change the product type in the first tab from "simple" to "configurable".

**Comment by wtdesign** [comment]
Thank you so much. I did not know, that I have to change the product type. That is why I coudn't see the backend variant selector in no product.

**Comment by wtdesign** [comment]
Is it possible to change the price for a special variant?

**Comment by extcode** [comment]
I'm not sure what you mean. Can you be more specific?

**Comment by wtdesign** [comment]
Now I'm not sure what you mean. My first problem is solved. 
My second problem was about different prices per variant. If I now select a variant in the frontend, the new price will not be shown. This is also not visible in the shopping cart.

I think this will be related to tx_cart_products but tx_cart is also involved I think. When I put something in cart.

**Comment by wtdesign** [comment]
All right. I have now seen that you can also use a dropdown to select which price is displayed. Thank you very much for your help.
