### ISSUE TITLE
Don't empty cart while developing

### ISSUE THREAD

**Issue by webian** [extcode/cart#302]
While developing is useful to not empty the cart after a order is created to save some time by example when testing payments.

I tried setting `preventClearCart` in the payment Typoscript setup and the cart doesn't empty but then, when I create another order, I get this error `You can not redeclare the order number of your cart.`

What I understood is that the error is produced because [the new generated order number is different from the one stored in php session](https://github.com/extcode/cart/blob/a271b232061f34242eaac741855cdb457f142144/Classes/Domain/Model/Cart/Cart.php#L297) that is the first generated order number.

**Comment by rintisch** [comment]
@extcode 
As I can see this issue seems to be solved with your answer and the feedback from the author. 
I suggest closing this ticket!?
