### ISSUE TITLE
CurrencyForm is displayed even when only one currency is configured

### ISSUE THREAD

**Issue by X-Tender** [extcode/cart#303]
## Bug Report

**Current Behavior**
When I only have 1 currency configured the currency dropdown get still displayed, there is some fluid logic in ti but it doesn't kick in.

`<f:if condition="{settings.currencies -> f:count()} > 1">`

The Reason is that the content of `settings.currencies` is
```
currencies {
            default = 1
            1 {
                code = EUR
                sign = €
                translation = 1.00
            }
        }
```
which lead a count of 2.

**Expected behavior/output**
The currency dropdown should not be visible of only 1 currency is configured

**Environment**
- TYPO3 version(s): 9.5.20
- cart version: 6.9.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX Catalina

**Possible Solution**
Maybe it should check if the count is > 2?

**Comment by rintisch** [comment]
This is solved with https://github.com/extcode/cart/commit/21da9d0d7cb54b29ae2d52fc93c62b506f9375fd (I did not read this ticket and made an own with #437)
