### ISSUE TITLE
Make submit button disable optional

### ISSUE THREAD

**Issue by X-Tender** [extcode/cart#304]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently when you click the "submit" button it gets disabled via JS. Now I implemented a client side validation and therefor I have to add a workaround to "re-enable" the submit button when the form was invalid to give the user the posiblity to resubmit it.

**Describe the solution you'd like**
Maybe via a data attribute on the submit button? like "data-no-disable-on-submit"

**Comment by rintisch** [comment]
After merging https://github.com/extcode/cart/commit/f904c9a0f3bbaa0c8b36b602853fe48484b7446e the JS is modularized. By removing the following line 
```html
<f:asset.script identifier="prevent-multi-submit" src="EXT:cart/Resources/Public/JavaScript/prevent_multi_submit.js" />
```
in your overwrite of `Resources/Private/Partials/Cart/CouponForm.html` you get the behaviour you are looking for

@extcode I think this issue can be closed.
