### ISSUE TITLE
wrong hook class in sendSellerMail

### ISSUE THREAD

**Issue by matin73** [extcode/cart#305]
there is some issue with pdf attachment in version for typo3 9 for seller. In file typo3conf/ext/cart/Classes/Service/MailHandler.php class for hook is wrong:

` if ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['cart']['getMailAttachmentsHook']) {
                foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['cart']['getMailAttachmentsHook'] as $_classRef) {`

it must be
`            if ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['cart']['MailAttachmentsHook']) {
                foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['cart']['MailAttachmentsHook'] as $_classRef) {`

**Comment by rintisch** [comment]
This ticket is quite outdated and the code has changed so I will close the ticket. You're welcome to reopen the ticket if you think this problem still exists.
