### ISSUE TITLE
Multiple tax entries.

### ISSUE THREAD

**Issue by X-Tender** [extcode/cart#312]
I stumbled uppon a tax issue which I can't explain myself where two tax entries with the same taxClass are created but with different tax values.

**Current Behavior**
When I submit an order the orderItem have just one tax in it. Also in the PDF invoice which is generated via cart_pdf is only one Tax listed.
When I try to get an order via findOneByOrderNumber on the itemRepository and look at the recieved data. Then I notice two tax entries in it (in tax and totalTax).

![image](https://user-images.githubusercontent.com/1413979/96601992-d6333d80-12f2-11eb-93c4-a4f13beac2e1.png)
![image](https://user-images.githubusercontent.com/1413979/96602026-dd5a4b80-12f2-11eb-8399-3deb3170e112.png)

The second one is the correct tax.
Both have the same class but the value is different.
I ask myself, where did the 2. (wrong one)  comes from.
Also when I regenerate the invoice pdf via the backend function it lists both taxes.

**Expected behavior/output**
Output the one and only correct tax

**Environment**
- TYPO3 version(s): 9.5.21 (One language)
- cart version: 6.9.2
- cart_payone version: 2.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS:  OSX 10.15.7

**Additional context**
I also hold a monologe on slack about the issue today 😄

**Comment by lorddoumer** [comment]
Same problem here with cart 6.11.0 and cart_pdf 4.1.0 - strangely the exact same configuration doesn't produce this error in another instance. 
@X-Tender did you manage to solve this issue?

**Comment by X-Tender** [comment]
I 'solved' the issue by picking the last tax entry and praying that it always is the correct one.

Its in this Template:
`/InvoicePdf/Order/Footer.html`
![image](https://user-images.githubusercontent.com/1413979/112352547-26139780-8ccb-11eb-9c5b-37b7f776aa5f.png)

**Comment by lorddoumer** [comment]
Was thinking about the same solution, but was hoping there would be a cleaner way, haha. But if you had done the same it seems to be working so far? Thanks!

**Comment by johfeu** [comment]
This is still an issue with the latest version. The problem is, that TCA for both fields, tax and total_tax, is configured to the same foreign_table and foreign_field.
My solution is to override TCA and have total_tax have its own foreign_field in the taxes table

In `my_package/Configuration/TCA/Overrides/tx_cart_domain_model_order_item.php`:
```php
$GLOBALS['TCA']['tx_cart_domain_model_order_item']['columns']['total_tax']['config']['foreign_field'] = 'item_total';
```


In `my_package/ext_tables.sql`:
```sql
#
# Table structure for table 'tx_cart_domain_model_order_tax'
#
CREATE TABLE tx_cart_domain_model_order_tax (
    item_total int(11) unsigned DEFAULT '0' NOT NULL,
);
```

This should be solved in the cart extension

**Comment by rintisch** [comment]
Sorry I do not really get the problem. I need a proper instruction how to reproduce this error.

**Comment by rintisch** [comment]
@johfeu Which version do you mean with  "latest"? Do you mean v8 or are you working with the `main` branch which will be working for TYPO3 v12?
