### ISSUE TITLE
Order Statistics fail to to load, with TypeError

### ISSUE THREAD

**Issue by Beltshassar** [extcode/cart#314]
Type declaration array on Extcode\Cart\Domain\Repository\Order\ItemRepository::findAll() makes BE Module "Order Statistics" fail with the following error.

```
(1/1) TypeError

Argument 1 passed to Extcode\Cart\Domain\Repository\Order\ItemRepository::findAll() must be of the type array, null given, called in ~/web/typo3conf/ext/cart/Classes/Controller/Backend/StatisticController.php on line 55

```

Tried 3 different typo3 installations:
Typo3: 9.5.23 / 9.5.21
PHP: 7.2.26

The backend module seems to work, if I remove the type declaration.

Best Regards

Ðaniel

https://github.com/extcode/cart/blob/32a8c99b30f93004bb18d725202fb2a490b4170c/Classes/Domain/Repository/Order/ItemRepository.php#L49

**Comment by extcode** [comment]
With next bugfix release this problem should disappear.
