### ISSUE TITLE
Cart 7.0.1 orderItem.orderNumber NULL

### ISSUE THREAD

**Issue by steffengrafe** [extcode/cart#317]
Hallo Daniel,
ich arbeite jetzt schon viele Jahre mit deiner EXT:cart, so weit so gut und super.
Folgendes Problem beim Upgrade von 9.5 auf 10.4 ist mir aufgefallen:
im Objekt orderItem sind die Werte für OrderNumber und orderDate NULL.
In cart\Resources\Private\Templates\Order\Order\Show.html stehen sie noch zur Verfügung - in cart\Resources\Private\Templates\Mail\Open\Buyer.html zB nicht mehr.

Hi Daniel,
I've been working with your EXT: cart for many years now, so far so good and great.
I noticed the following problem when upgrading from 9.5 to 10.4:
in the orderItem object, the values ​​for OrderNumber and orderDate are NULL.
They are still available in cart\Resources\Private\Templates\Order\Order\Show.html - in cart\Resources\Private\Templates\Mail\Open\Buyer.html, for example, they are no longer available.

Cart 7.0.1
TYPO3 10.4.12

**Comment by boettner-it** [comment]
seems to work by changing the event order in Services.yaml. See the attached patch.

[local_history.patch.txt](https://github.com/extcode/cart/files/5956892/local_history.patch.txt)

**Comment by extcode** [comment]
OK, I'll fix that. The order isn't well defined here. Both, cart--process-order-create--order-number and cart--process-order-create--email are defined to run after cart--process-order-create--order.
