### ISSUE TITLE
Impossible to override fluidemail paths

### ISSUE THREAD

**Issue by georgringer** [extcode/cart#327]
it is impossible to override the fluid emails as the extension from current request will come last
![image](https://user-images.githubusercontent.com/1905663/110316777-7ae8ba00-800b-11eb-8c2c-7744c9601e3d.png)

I propose to provide a custom TemplatePaths object and take a custom setting into account + removing setting typo3_conf_vars in `ext_localconf.php`.

**Comment by mschwemer** [comment]
Same here. It would be cool having a solution for this. 

I am happy to test a solution. :-) 

Thx for your great extension!

**Comment by KaffDaddy** [comment]
You could overwrite the templates/partials/layouts via TYPO3_CONF_VARS like
```
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['layoutRootPaths'][1632915465] = 'EXT:sitepackage/Resources/Private/Layouts/Mail';
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['partialRootPaths'][1632915465] = 'EXT:sitepackage/Resources/Private/Partials/Extensions/Cart';
 ```

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Doesn't work here too, also not with changing TYPO3_CONF_VARS in a custom extension like described here:

https://docs.typo3.org/p/extcode/cart/main/en-us/Changelog/7.0/Breaking-288-ChangeMailHandlerToFluidEmail.html?highlight=template

Workaround for now is to patch `ext_localconf.php` of EXT:card and add the lines there, f.e.:

$GLOBALS['TYPO3_CONF_VARS']['MAIL']['partialRootPaths']['1600000000'] = 'EXT:myext/Resources/Private//Extensions/Cart/Partials/';

Last but not least, documentation lacks information about overriding fluidemails completely. ;-)

**Comment by geri777** [comment]
Same problem here. No fix for almost 1 year...

**Comment by rintisch** [comment]
@geri777 
Your problem does not seem to be the same as the original problem. What you are confronted with is simply Fluidemail. You do not need the workaround because EXT:cart does not define a layout for mails. You can by the way define your own logo in the backend of TYPO3 (have a look in the Extension configuration → backend → loginLogo)

**Comment by rintisch** [comment]
@extcode 
It's working for me in the current main branch
![image](https://github.com/extcode/cart/assets/44193208/2239e4bd-45f5-4154-a4b4-1053a3d7870e)


@georgringer 
Do you have the possibility to test it?

My setup:

`ext_localconf.php`:
```php
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['partialRootPaths']['1588829281'] = 'EXT:cartintegration/Resources/Private/Partials/';
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['templateRootPaths']['1588829281'] = 'EXT:cartintegration/Resources/Private/Templates/';
```

And the tree under `Resources/Private/`:

```
├── Partials
│   └── Mail
│       └── Address.html
└── Templates
    └── Mail
        └── Open
            └── Buyer.html
```

**Comment by rintisch** [comment]
I will close this issue because this is solved at the moment and no negative feedback came in.
