### ISSUE TITLE
{orderItem.additionalData} results in TypeError

### ISSUE THREAD

**Issue by machwatt** [extcode/cart#330]
## Bug Report

**Current Behavior**
Using `{orderItem.additionalData}` in the backend module template causing: TypeError: Return value of Extcode\Cart\Domain\Model\Order\Item::getAdditionalData() must be of the type string, null returned.

e.g. `<f:if condition="{orderItem.additionalData}">{orderItem.additionalData}</f:if>`

**Expected behavior/output**
No exception should appear.

**Environment**
- TYPO3 version(s): 10.4.14
- cart version: 7.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: OSX and Ubuntu

**Possible Solution**
The getter `Item::getAdditionalData()` should allow null value as return (`public function getAdditionalData(): ?string` or the database default for text should be empty string.

**Comment by extcode** [comment]
II fixed the error by presetting the variable with an empty string.
