### ISSUE TITLE
PHP Fatal error because of not existing method

### ISSUE THREAD

**Issue by garfieldius** [extcode/cart#332]
## Bug Report

**Current Behavior**
When generating an invoice, with EXT:cart_pdf, for an order item that has no invoice number, EXT:cart wants to generate one, but then the process fails because the method `$this-generateNumber`  does not exist.

The problem is in \Extcode\Cart\Controller\Backend\Order\DocumentController::createAction, line ~55. The method `generateNumber` exists in the OrderController.

**Environment**
- TYPO3 version: 10.4.13
- cart version: 7.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux (Docker)

**Possible Solution**
Move the method into an abstract controller or a trait that is extended or used by both OrderController and DocumentController

**Comment by extcode** [comment]
Will be fixed in Version 7.5.0, 6.13.1 and 5.9.4.
