### ISSUE TITLE
Remove jQuery as a Dependency

### ISSUE THREAD

**Issue by andyhausmann** [extcode/cart#333]
## Bug Report

**Current Behavior**
If one is developing a project with vanilla JS, functionality will brick because this EXT has a hidden dependency to jQuery.

**Expected behavior/output**
Refactor cart.js to vanilla JS.

**Environment**
- TYPO3 version(s): multiple
- cart version: multiple
- Is your TYPO3 installation set up with Composer (Composer Mode): irrelevant
- OS: irrelevant

**Possible Solution**
Refactor cart.js.

**Additional context**
None

**Comment by rintisch** [comment]
Have not tested that yet but at least the description looks promising:
https://github.com/sachinchoolur/replace-jquery

**Comment by rintisch** [comment]
@extcode 
After merging the PR this issue can be closed now :)
