### ISSUE TITLE
Different shipping address is not mapped into the confirmation email

### ISSUE THREAD

**Issue by tobikummer** [extcode/cart#335]
## Bug Report

**Current Behavior**
If I add different addresses (billing !== shipping), the email has just one address (billing address) and says, that the addresses are the same.

**Expected behavior/output**
The two different addresses should be displayed in the confirmation email

**Environment**
- TYPO3 version(s): 10 LTS
- cart version: 7.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: CentOS Linux 7.9.2009

**Possible Solution**
Don't know exactly about the logic of this extension. But if I debug [here](https://github.com/extcode/cart/blob/master/Classes/Controller/Cart/OrderController.php#L123) 
$orderItem is a function parameter, $this->cart is restored from session.
`DebuggerUtility::var_dump($orderItem['shippingSameAsBilling']); => FALSE`
`DebuggerUtility::var_dump($this->cart->isShippingSameAsBilling()); => TRUE` 
That should really not be different, this two values.
Why is there a difference? The $orderItem does it right, the restored-from-session $this->cart does it wrong… And, proceed the process, the “shipping-address” in the confirmation email is empty

**Comment by extcode** [comment]
I cannot reproduce this error.
If you check/uncheck the checkbox, a request should be sent to cart/country controller.
Is this also done in your installation?
![Bildschirmfoto_2021-05-21_07-00-12](https://user-images.githubusercontent.com/1134172/119084724-9a846180-ba02-11eb-91a2-5f5c38183cbd.png)
