### ISSUE TITLE
When Using AJAX Mini cart doesn't update

### ISSUE THREAD

**Issue by HenryAveMedi** [extcode/cart#346]
When Using AJAX Mini cart doesn't update
any idea to what i have to do to access the new cart object and render it in the mini cart?

**Current Behavior**
when adding object to the cart per ajax, the minicart does not update

**Expected behavior/output**
when adding object to the cart per ajax, the minicart should fetch the new {cart} per ajax as well

**Environment**
- TYPO3 version(s): 10.4.15
- cart version: 7.1.8
- cart_products: 3.0.0 

**Possible Solution**

**Additional context**

**Comment by dahaupt** [comment]
In general, retrieving the mini-cart via AJAX would be beneficial, so that a static cache (e.g. via ext:[staticfilecache](https://extensions.typo3.org/extension/staticfilecache)) can still be used.

**Comment by rintisch** [comment]
@HenryAveMedi
The JS should update the minicart but you have to follow the syntax which is demanded by the JavaScript:
https://github.com/extcode/cart/blob/f1e76da8b29423b2319d470f5b3c1ff777f5d2cf/Build/Sources/JavaScript/add_to_cart.js#L108-L112

Did you follow those requirements but it's still not working?

**Comment by rintisch** [comment]
I will close this ticket due to missing feedback. You're off course still welcome to respond!

**Comment by rintisch** [comment]
@dahaupt I now realized that you can use https://github.com/studiomitte/cart_count to have fully cached pages.
