### ISSUE TITLE
Order Number and Order Date missing in Order Email

### ISSUE THREAD

**Issue by matin73** [extcode/cart#352]
I am using TYPO3 10.4.x and latest Cart extension. Works fine, but Order Number and Order Date missing in Order Email:
![grafik](https://user-images.githubusercontent.com/3177275/137724105-b7fc6658-0712-4bd4-8b8a-825b7fe58aac.png)

**Comment by rintisch** [comment]
@matin73 
This seems to be solved in between with fluid mail
![image](https://github.com/extcode/cart/assets/44193208/dc8ab86f-d887-4d37-b8c6-ef04991b30d9)

So I will close this ticket. You're welcome to reopen it if your problem still occurs.
