### ISSUE TITLE
BE cart: overwrite backendmodul template does not work

### ISSUE THREAD

**Issue by EnzephaloN** [extcode/cart#367]
I tried to overwrite templateRootPaths for Backendmodule by adding `module.tx_cart.view.templateRootPaths.10 = EXT:mytheme/Resources/Private/Extensions/cart/Backend/Templates/`to typoscript-setup. But this template isn't used in backend. 
What more is to be done?

**Comment by rintisch** [comment]
I can give an answer for the coming v9 (working with TYPO3 v12):

This version will use the ModuleTemplate API, see https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96730-SimplifiedExtbackendModuleTemplateAPI.html#feature-96730-simplified-ext-backend-moduletemplate-api

This changelog links https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96812-OverrideBackendTemplatesWithTSconfig.html

According to this you need to have an own extension with

```php
// in your ext_localconf.php

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig(
    '<INCLUDE_TYPOSCRIPT: source="FILE:EXT:myext/Configuration/TsConfig/Page/page.tsconfig">'
);
```

```tsconfig
templates.extcode/cart.1645483508 = vendor/myext:Resources/Private/TemplateOverwrites
```

and in `myext/Resources/Private/TemplateOverwrites/Templates/Backend/Order/Order/List.html` you can make the overwrite for `cart/Resources/Private/Backend/Order/Order/List.html`.

I tested it and it works. I will close this ticket as solved.
