### ISSUE TITLE
BE Cart Module throws PHP Runtime Deprecation Notice: strtolower()

### ISSUE THREAD

**Issue by abohntek** [extcode/cart#372]
## Bug Report

**Current Behavior**
Got following error appears when accessing the backend cart module or the extension module

`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/website/current/html/typo3/sysext/core/Classes/Imaging/IconRegistry.php line 616`

**Expected behavior/output**
no error message, orders or extensions shall be listed.

**Environment**
- TYPO3 version(s): 11.5.7
- cart version: 8.2.0
- PHP: 8.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Possible Solution**
the way of adding the main BE module has to be changed inside ext_tables.php to:

```
// Register icon for main BE module 
    $svgProvider = \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class;
    $modulePrefix = 'extensions-cart-module';
    $extIconPath = 'EXT:cart/Resources/Public/Icons/';
    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class);
    $iconRegistry->registerIcon(
        $modulePrefix . '-main', 
        $svgProvider, 
        ['source' => $extIconPath . 'module.svg']
    );

    // Add Main module "Cart". <- new way of adding main BE module, fixing excpetions. Code taken from solr extension
    // Acces to a main module is implicit, as soon as a user has access to at least one of its submodules. To make it possible, main module must be registered in that way and without any Actions!
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModule(
        'Cart',
        '',
        '',
        null,
        [
            'name' => 'Cart',
            'labels' => $_LLL_db . 'tx_cart.module.main',
            'iconIdentifier' => 'extensions-cart-module-main'
        ]
    );
    /*
    // add Main Module <- old buggy way that causes exceptions!
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule(
        'Cart',
        'Cart',
        '',
        '',
        [],
        [
            'access' => 'user, group',
            'icon' => 'EXT:cart/Resources/Public/Icons/module.svg',
            'labels' => $_LLL_db . 'tx_cart.module.main',
        ]
    );
    */
```

Can u include that for the next release?

**Comment by tastensolo** [comment]
This issue still exists for the setup mentioned above. 
The way of putting the main BE module after the file Module inside ext_tables.php is not possible:

**Solution:**Please remove this codeblock from :
`    if (!isset($GLOBALS['TBE_MODULES']['_configuration']['Cart'])) {
        $temp_TBE_MODULES = [];

        foreach ($GLOBALS['TBE_MODULES']['_configuration'] as $key => $val) {
            $temp_TBE_MODULES[$key] = $val;
            if ($key === 'file') {
                $temp_TBE_MODULES['Cart'] = '';
            }
        }

        $GLOBALS['TBE_MODULES']['_configuration'] = $temp_TBE_MODULES;
    }`

Can u remove it please?

**Comment by extcode** [comment]
I'll have a look next week.

**Comment by extcode** [comment]
In a fresh composer installation I got the error, was able to reproduce it and removed the part from the code for v7.x and v8.x of the cart extension.
