### ISSUE TITLE
Submitting the order with the new "steps" feature throws an error

### ISSUE THREAD

**Issue by HenryAveMedi** [extcode/cart#376]
When i finish the order steps and submit the order in step 4, it throws the following error:

```
Oops, an error occurred!
An action "showStep4Action" does not exist in controller "Extcode\Cart\Controller\Cart\CartController".

More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1186669086).
```

**Comment by extcode** [comment]
Can you provide some more information about this Error. Can't find a link to the showStep4Action. Did you change the templates?
Do you use a payment provider extension? You can also send information that you don't want to be public to me in Slack.

**Comment by HenryAveMedi** [comment]
I use own templates, yes, but also didn't find that argument in my templates, turned urs off and had the same problem. Today i replayed the whole thing again and it worked without problems, i think the problem was that i was opening the edits in 4th step into new tabs and going back and forth between tabs, that might have changed something in the cookie/saved object. This might be worth knowing as well.

So, all is well, and here this info that might be valuable in the future

**Comment by dahaupt** [comment]
I get a similar error if the (Extbase) validation of the billing address fields reports an error. Then the `errorAction` is executed, which forwards to the referring requests. But this does not work, because the value of the referrer action is e.g. `showStep2`, which does not exist. I have created a new issue #382 for this.
