### ISSUE TITLE
How to change OrderNumber offset (Services.yaml question)?

### ISSUE THREAD

**Issue by s0njar0** [extcode/cart#387]
Hey!
I'm using the cart extension for a few years now and I was used to add an offset of 10000 to the order number via Typo3 Constants. But now this is not working anymore. Today I learned that I have to change it via Services.yaml, but when I create my own Services.yaml with the following content it doesn't work:

services:    
  Extcode\Cart\EventListener\Order\Create\OrderNumber:
    arguments:
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'
      $options:
        offset: 10000
    tags:
      - name: event.listener
        identifier: 'cart--order--create--order-number'
        event: Extcode\Cart\Event\Order\NumberGeneratorEvent
        after: 'cart--order--create--order'

It's working when I add this offset option to Services.yaml of cart extension, but this can't be the correct way. How can I get Typo3 to use my Services.yaml for this? I checked the Typo3 docs already, but it didn't help.

**Comment by extcode** [comment]
Does your site package extension have the extcode/cart as a dependency?

**Comment by s0njar0** [comment]
You mean I have to add it in ext_emconf.php?

**Comment by extcode** [comment]
Do you have a composer based installation? You have to add the dependency as composer requirement as well.
Did the PackageStates.php list your Site Package Extension after the cart-Extension? If not, you have to generate the PackageStates.php again.
Did you clean the Cache in the Install Tool / Maintenance Module? The Dependency Injection Cache File has to be generated again. In var/cache/code/di/ the generated File should then contains something like:
```
    /**
     * Gets the public 'Extcode\Cart\EventListener\Order\Create\OrderNumber' shared autowired service.
     *
     * @return \Extcode\Cart\EventListener\Order\Create\OrderNumber
     */
    protected function getOrderNumberService()
    {
        return $this->services['Extcode\\Cart\\EventListener\\Order\\Create\\OrderNumber'] = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstanceForDi(\Extcode\Cart\EventListener\Order\Create\OrderNumber::class, ($this->services['TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager'] ?? $this->getPersistenceManagerService()), ($this->services['Extcode\\Cart\\Domain\\Repository\\Order\\ItemRepository'] ?? $this->getItemRepositoryService()), ($this->privates['Extcode\\Cart\\Utility\\OrderUtility'] ?? $this->getOrderUtilityService()), ['offset' => 10000]);
    }
 ```

**Comment by s0njar0** [comment]
> Do you have a composer based installation?

No.

> you have to generate the PackageStates.php again

How can I do this?

**Comment by extcode** [comment]
Not sure for non composer based installations. I used helhum/typo3-console for a long time.
I think deactivating (deinstalling) and (installing) activating an extension (e.g. cart-extension) will do this in the extension manager.
You have to clean the cache in the Install Tool or in the Maintenance Module after that, to be sure that the Dependency Injection file will be generated again.

**Comment by s0njar0** [comment]
Thank you so much, it works now! 😊
