### ISSUE TITLE
German translation went wrong

### ISSUE THREAD

**Issue by tobikummer** [extcode/cart#398]
## Bug Report

**Current Behavior**
After the deployment of the project, we execute the cli task "language:update". We get the translated files fro the translation server. These files are empty! So the output on the website (and in the TCA) is in english.

**Expected behavior/output**
Translation file is filled with valid content.

**Environment**
- TYPO3 version(s): 10.4.30
- cart version: 7.7.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux Server & local ddev env

**Possible Solution**
-

**Reproduce**
Just run ```ddev typo3cms language:update``` on your local machine and have a look into the translation files in ```/var/labels/de/cart/Resources/Private/Language/*```

**Comment by extcode** [comment]
The translation of extcode/cart, extcode/cart_books, extcode/cart_events, and extcode/cart_products switched to Crowdin.
I had some trouble with proofreading existing translations. The export to the translation server only exports proofreaded translation. If no proofreaded translation is available, the translation file has an empty body.
Please run language:update again.

**Comment by tobikummer** [comment]
YES, works for me now! thank you!!
