### ISSUE TITLE
missing label key / typo

### ISSUE THREAD

**Issue by TrueType** [extcode/cart#411]
https://github.com/extcode/cart/blob/d7941b9fb6edeb9a7ed0196bae393d1ad043bc80/Configuration/TCA/tx_cart_domain_model_order_product.php#L43

label key product_id may not be set .. there is a key productId.

**Comment by rintisch** [comment]
@TrueType 
This is solved with https://github.com/extcode/cart/commit/738dd5aecf1c27bddab98dee500cb30704ec05be

@extcode 
This issue can be closed.
