### ISSUE TITLE
Support for TYPO3 v12.

### ISSUE THREAD

**Issue by jaumepresaspuig** [extcode/cart#413]
## Feature Request

Is cart going to have support for TYPO3 v12?

**Comment by der-phillip** [comment]
Hello, what is the status here?

**Comment by markussoeth** [comment]
I also would like to know, if I need to switch to another extension.

**Comment by rintisch** [comment]
@ms-wa Where does this information come from? Who will do the work?

**Comment by ms-wa** [comment]
@rintisch I had a short conversation with extcode. 
They told me this, but I did not know an exact release date.

**Comment by sneopu** [comment]
Any news on this subject? Is there a way we can help? Perhaps sponsoring?

**Comment by rintisch** [comment]
@sneopu 
I made some PRs in between but unfortunately they do not get merged any longer. extcode does not seem to have enough time.

To solve this for my own I started to merge them in my own fork. I will also merge the commits from extcode which replace the hooks with events asap (having problems to merge them at the moment). 

https://github.com/rintisch/cart/tree/develop

This way the extension works for me without errors but it might be interesting to see whether it works for others as well. Feedback is welcome!
You might want to have a look an prepare your own updates until the official repos gets updated? That's at least what I will do to get progress...

I plan to do the same for `extcode/cart_products`

**Comment by rintisch** [comment]
This is solved, you can now use https://github.com/extcode/cart/tree/v9.0.0 as TYPO3 v12 compatible version.

**Comment by markussoeth** [comment]
Thank you very much for supporting this projekt!
Please do the same for extcode/cart_products 💯

**Comment by rintisch** [comment]
@markussoeth 
It's ongoing. Of course would EXT:cart and the other sub-extensions even better with more support from the community. It's starts with writing good issue, making pull requests, writing documentation (no developer experience needed at all!) up to donating for the project. 
This project can thrive with a living community!
