### ISSUE TITLE
German translation contains english words

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [extcode/cart#418]
The german translation has copy and paste leftovers "net" and "gross" in the following lines:

https://github.com/extcode/cart/blob/d7941b9fb6edeb9a7ed0196bae393d1ad043bc80/Resources/Private/Language/de.locallang.xlf#L129

https://github.com/extcode/cart/blob/d7941b9fb6edeb9a7ed0196bae393d1ad043bc80/Resources/Private/Language/de.locallang.xlf#L133

**Comment by rintisch** [comment]
This is solved with https://github.com/extcode/cart/commit/80924f695c2f63c2869658da66235dc90bf31c06. Now you need to download the language pack to get the labels from Crowdin.

Thanks for you contribution!
