### ISSUE TITLE
Undefined array key "options"

### ISSUE THREAD

**Issue by ToGetATockenOnly** [extcode/cart#424]
PHP Warning: Undefined array key "options" in /var/www/html/stl-statistik/web/current/webroot/public/typo3conf/ext/cart/Classes/Controller/Cart/OrderController.php line 75

With PHPv8.1 and exceptionalErrors = 12209 (standard value is 4096, where such errors are not shown) the code runs into erros on several occasions.

**Comment by rintisch** [comment]
@ToGetATockenOnly this should be solved in the current main branch and also for 8.x with the patch https://github.com/extcode/cart/commit/031a752e6ef03adb76ac29fc2d4c0a96e19e2c39

I will close the issue, you are welcome to reopen if you think this is a wrong decision.
