### ISSUE TITLE
Upgrade for 12LTS in view of 13; publish a schedule

### ISSUE THREAD

**Issue by vmans** [extcode/cart#433]
Upgrade for compatibility with 12LTS and with respect to the already known changes for version 13.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog-12.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog-13.html

Publish a schedule, a plan of action.

**Comment by extcode** [comment]
A release for TYPO3 v12 will probably take place in February. TYPO3 v13 will then follow soon, as there is a project where cart and cart-events could be used. An offer has been sent to the customer.

**Comment by extcode** [comment]
We had some open issues to fix. Please be patient for a few more days.

**Comment by rintisch** [comment]
As note for v13:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Breaking-102605-TSFE-fe_userRemoved.html?highlight=globals%20tsfe%20fe_user

**Comment by terminal8-nz** [comment]
Are there news about the schedule?

I see that there's a lot going on, so thank you for your work! Just wanted to know if the release of the new version is to be expected soon or if there are bigger problems that require more time.

**Comment by rintisch** [comment]
I can unfortunately not say anything about the schedule, I am just delivering PRs. @extcode as owner is responsible for the merges and I do not know his schedule.

**Comment by rintisch** [comment]
https://github.com/extcode/cart/tree/v9.0.0 is a stable version compatible with v12. Some work for v13 is already done and further steps are in the pipeline.
