### ISSUE TITLE
Add linting for JS files

### ISSUE THREAD

**Issue by rintisch** [extcode/cart#448]
## Feature Request

**Is your feature request related to a problem? Please describe.**
JS files has no linting yet which is suboptimal in an OS project.

**Describe the solution you'd like**
Add linting rules and check them in Github Action.

**Comment by extcode** [comment]
I've added GitHub Action CI configuration right now. What tool I need for JS linting?

**Comment by rintisch** [comment]
I am a newby on this area so I will need to dig before I can answer :)
