### ISSUE TITLE
required field by variants

### ISSUE THREAD

**Issue by celmedia** [extcode/cart#48]
variants need to have a required field.

**Comment by extcode** [comment]
Which variants do you mean? The frontend variants have a checkbox but in the current version there is no validation on server side. Only client side html5 oder javascript validation is possible. Backend variants do not have such an checkbox yet.

**Comment by celmedia** [comment]
you also can see it here that the second product has a drop down ... and because i cant make a empty variant first in backend ... there is no way that i know to write a required field to it because it already always has somthing in it like the variant "Bitte wählen"  or do you have a other solution for it ? thanks 
here the shop : http://trivanti.cel-media.ch/shop/

**Comment by extcode** [comment]
Solved with version 3.0.0.
