### ISSUE TITLE
Declaration of FieldNameViewHelper::render() should be compatible with ActionViewHelper::render

### ISSUE THREAD

**Issue by eckonator** [extcode/cart#5]
Hi,
i try yout cart Extension on my TYPO3 Projekt based on 7.6.9 LTS and PHP 7.2. I get the following error when i try to add a product in my cart.

#1: PHP Warning: Declaration of Extcode\Cart\ViewHelpers\FieldNameViewHelper::render() should be compatible with TYPO3\CMS\Fluid\ViewHelpers\Link\ActionViewHelper::render($action = NULL, array $arguments = Array, $controller = NULL, $extensionName = NULL, $pluginName = NULL, $pageUid = NULL, $pageType = 0, $noCache = false, $noCacheHash = false, $section = '', $format = '', $linkAccessRestrictedPages = false, array $additionalParams = Array, $absolute = false, $addQueryString = false, array $argumentsToBeExcludedFromQueryString = Array, $addQueryStringMethod = NULL) in /var/www/clients/client5/web13/web/html/typo3conf/ext/cart/Classes/ViewHelpers/FieldNameViewHelper.php line 0

**Comment by extcode** [comment]
I think the problem raises cause the ViewHelper extending from \TYPO3\CMS\Fluid\ViewHelpers\Link\ActionViewHelper instead of \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper.

The error should raise every time the cart will be shown. I have created a branch issue_5.

**Comment by eckonator** [comment]
You're right. This ViewHelper was used only one time, so i comment it out and after this i can access the cart page.

New problem i have seen there, is that there is a chechbox vor the delivery address, but the form for this address is never been shown. Are this problems occours because i use php7 or typo3 7.6? Run your extension better on 6.2?

Greetings, Markus

**Comment by extcode** [comment]
Hi Markus,

can you test the change in branch issue_5?
The extension should working in 7.6. The most frontend testing is done in TYPO3 7.6, but not with php7 yet. But every error reporting for php7 is wellcome.

The form for the shipping address is there, but is hidden by default. I decide to provide a little cart.js javascript file. This is an example and is not included by default. The reason is that everybody loads jQuery differently, or use another javascript libraries. You can include the cart.js from Public/JavaScripts/Default/cart.js or add your own javascript.

For further questions I also have a slack channel (https://typo3.slack.com/messages/ext-cart/).

**Comment by eckonator** [comment]
Hi Daniel, good to now the Info with the cart.js file. My first impression of your extension is really good. Before i got the tip on facebook to your extension, i was testing other extension like multishop or quick_shop, but all was too big for my wishes, or add more and more extenstions to typo3 or not based of extbase/fluid or not ready for 7.6. I hope i get a simple shop running with your ext. Are you on facebook? Maybe we can speak there further in german?

Greetz Markus

**Comment by eckonator** [comment]
I will test your new branch tomorrow and give you feedback:)

Thanks for your work and help!
Markus

**Comment by extcode** [comment]
No, no facebook. Send me an email and we find a better way for communication.

**Comment by eckonator** [comment]
New error after checking out issue_5:

 Property Extcode\Cart\ViewHelpers\FieldNameViewHelper::$tag does not exist

**Comment by extcode** [comment]
I think this was an ClearCacheProblem cause the ViewHelpers will be cached by TYPO3. Version 0.7.5 should fix this issue.
