### ISSUE TITLE
Custom Email Partial ignored

### ISSUE THREAD

**Issue by matin73** [extcode/cart#550]
I have setup custom partial template for example Summery in OrderForm which is working. But custom template in Resources/Private/Partials/Mail are ignored

**Comment by rintisch** [comment]
Have you followed what I wrote in https://github.com/extcode/cart/issues/327#issuecomment-2020960478 and what is as well written in https://docs.typo3.org/p/extcode/cart/main/en-us/Administrator/Configuration/Email/OverwriteEmailTemplates/Index.html?

**Comment by matin73** [comment]
sorry, did not see this part of configuration. thanks! working fine!
