### ISSUE TITLE
add_to_cart.js not loaded

### ISSUE THREAD

**Issue by peterschoene** [extcode/cart#553]
## Bug Report

**Current Behavior**
When I follow your guide from youtube-video, I get at timecode 5:43 only a message like this:
{
  "status": "200",
  "added": 1,
  "count": 2,
  "net": 21.6806722689076,
  "gross": 25.8,
  "productsChanged": {
    "CartProducts_1": {
      "productType": "CartProducts",
      "productId": 1,
      "id": "CartProducts_1",
      "sku": "4017029307016",
      "title": "Produkt",
      "price": 12.9,
      "specialPrice": 12.9,
      "quantityDiscounts": [],
      "taxClass": {

      },
      "quantity": 2,
      "price_total": 25.8,
      "price_total_gross": 25.8,
      "price_total_net": 21.6806722689076,
      "tax": 4.11932773109244,
      "additional": []
    }
  },
  "messageBody": "Item was added to cart.",
  "messageTitle": "",
  "severity": 0
}

The Message will not be rendered and the AJAX isn't working. I don't see the green message, just the json-Output

**Expected behavior/output**
I expect the behavior from Youtube-Video timecode 5:43.

**Environment**
- TYPO3 version(s): 12.4.17
- cart version: 9.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Solution**
Problem seems to be, that add_to_cart.js isn't loaded before DOM ist completed. Don't know why
I added it via includeJSFooter.tx_cart = EXT:cart/Resources/Public/JavaScript/add_to_cart.js

**Comment by rintisch** [comment]
The video is partly outdated. Please follow the instructions below as well. The JS is not loaded any longer that way. It was split up while jQuery was removed. Please see also the Breaking Change for version 9.0.0

**Comment by rintisch** [comment]
@peterschoene could you solve the problem?

**Comment by rintisch** [comment]
@peterschoene I guess I understand your problem now. You are using EXT:cart_products aren't you? In this case the bugfix https://github.com/extcode/cart_products/pull/184 could help you.

**Comment by rintisch** [comment]
I will close this issue as i got no feedback within 2 weeks. You are welcome to reopen it!
