### ISSUE TITLE
Wrong sum for variants with stock limit

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#554]
## Bug Report

**Current Behavior**
I have a product with several colour variants. I activated `Stock handling in variants`. Each variant has a stock of 1. For example, if I select a product with a yellow color and one with a blue color, both color variants are displayed correctly with price in the cart form. The line below, which should show the sum of the two products, shows the correct quantity, i.e. `2`, but the sum of the two products is `0`. 

When listing the total price, the price for the two color variants is missing. In addition, the order button is no longer displayed.

In the detailed view of a product, only one product can be ordered as there is only one product in stock. A corresponding message appears. However, the number of products can be increased in the shopping cart without a corresponding message appearing.

**Expected behavior/output**
The sum should be displayed correctly, as should the order button. It should only be possible to increase the number of products in the shopping cart if there is a corresponding number of products in stock.

**Environment**
- TYPO3 version(s):12.4.17
- cart version: 9.0.0.
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- I use the original templates of cart

**Comment by extcode** [comment]
I guess this is an issue related to cart-products. I fixed an issue there. Please try to update to cart-products version 5.0.0 and test the stock handling again.

**Comment by extcode** [comment]
Can you provide me with more information/screenshots on where exactly the problem occurs? Also via DM in Slack.

**Comment by Hobokens** [comment]
The problem is solved with the new version for TYPO3 12.
