### ISSUE TITLE
[HOWTO] add a button to backend-module for XML-export

### ISSUE THREAD

**Issue by EnzephaloN** [extcode/cart#588]
Hello
Sorry, slack won't work on my machines, so I have to ask here.

In the past I tried to add a XML-export-button to backend-module by overriding backend-module-templates. This does not work anymore. The default-button is generated by $this->getListButtons() in OrderController. This is nice, but how can I add an own button to DocHeader for exporting orders as XML? Or is there any other extension which handles a XML-export?

Kindly regards
EnzephaloN

**Comment by EnzephaloN** [comment]
Hello and thank you.
This looks good. I hope you can merge this soon and maybe give us a little howto-documentation.
Kindly regards
EnzephaloN

**Comment by rintisch** [comment]
Hey,
just as info: extcode will make an improved version of my PR which will get merged.

**Comment by extcode** [comment]
I have created my own PR based on @rintisch work. I will discuss this with him. I am uncomfortable passing $this to an event and also think that a special event to modify the ButtonBar is what was requested as an feature here. I use the event itself in the PR, so theoretically it should be possible to replace the CSV export with a custom XML export.
I have also used the event for the buttons in the showAction so that it be possible to add own buttons to this action as well.

**Comment by EnzephaloN** [comment]
Hello @extcode .
I'm curious about it and hope that you can give me a howto for adding a XML-export ;-)
best regards
EnzephaloN

**Comment by extcode** [comment]
I merged the PR. If you want to add your own button with your own action, you can have a look to `\Extcode\Cart\EventListener\Template\Components\ModifyButtonBar`. The extension use it's own event to add the buttons to DocHeader section.
I will add a second new event with another ticket. If this is finished, I will release both together.

**Comment by EnzephaloN** [comment]
Thanx for your great work!

**Comment by EnzephaloN** [comment]
Great work, but I'm too stupid for getting it done ;-)

If have Services.yaml
````
services:
  EnzephaloN\Tbf\EventListener\Cart\ModifyOrderListButton:
    tags:
      - name: event.listener
        event: Extcode\Cart\Event\Template\Components\ModifyButtonBarEvent
        identifier: 'cart--cart--template--components--modify-button-bar'
````
I have ModifyOrderListButton.php
````
<?php

namespace EnzephaloN\Tbf\EventListener\Cart;

use Extcode\Cart\Event\Template\Components\ModifyButtonBarEvent;
use TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder;

final class ModifyOrderListButton{

    public function __construct(
        private readonly UriBuilder $uriBuilder
    ) {}

    public function __invoke(ModifyButtonBarEvent $event){
        $request = $event->getRequest();
        if ($request->getControllerName() !== 'Backend\Order\Order') {
            return;
        }
        if ($request->getControllerActionName() === 'list') {
            $this->modifyListActionButtons($event);
            return;
        }
    }

    private function modifyListActionButtons(ModifyButtonBarEvent $event): void
    {
        $event->setButtons(
            array_merge(
                $event->getButtons(),
                [ 'action-export-xml' => [
                    'link' => $this->uriBuilder->reset()->setRequest($event->getRequest())
                        ->setArguments(['searchArguments' => $event->getSearchArguments()])
                        ->setFormat('xml')
                        ->uriFor('export'),
                    'title' => 'Export XML',
                    'icon' => 'actions-download',
                    'group' => 1,
                    'showLabel' => true,
                ],
                ]
            )
        );
    }

}
````
And I've an Export.xml in my extension.

But I do not see my button. What I've missed to write?
