### ISSUE TITLE
Checkout-Problems with cart 9.0.3 phpstan/phpdoc-parser 2.0 

### ISSUE THREAD

**Issue by sitsCHO** [extcode/cart#599]
The Checkout breaks on phpstan/phpdoc-parser 2.0 which is shipped with TYPO3 12.4.23 in composer based installations.

Downgrade to phpstan/phpdoc-parser 1.33.0 fixed the problem.

**Comment by rintisch** [comment]
This is not a problem which is related to EXT:cart so this Ticket can be closed. A tip how to fix it comes with https://typo3.org/article/typo3-1341-and-12423-maintenance-releases-published
