### ISSUE TITLE
Problem with the basket

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#6]
Hi,
thanks for the nice new shop extension. It will be perfect for my small shop.
I installed it with PHP 7.0.6, TYPO3 7.6.10 and the Bootstrap_Package.

Now I get the following errror message for every page:

`Core: Error handler (FE): PHP Warning: Declaration of Extcode\Cart\Domain\Model\FileReference::setOriginalResource(TYPO3\CMS\Core\Resource\FileReference $originalResource) should be compatible with TYPO3\CMS\Extbase\Domain\Model\FileReference::setOriginalResource(TYPO3\CMS\Core\Resource\ResourceInterface $originalResource) in /html/typo3/typo3conf/ext/cart/Classes/Domain/Model/FileReference.php line 24`

In FE I get within the 
`<div class="container mit_korb"></div>`
the error message
`Oops, an error occurred! Code: 20160819123653e6610eb3 `

Activating the debugging in the install tool the 'Basket' isn't shown anymore and I get the error meassage `Oops, an error occurred! Code: 20160819125544614b3cba`

Regards
Hobokens

**Comment by extcode** [comment]
I will have a look on that in the evening.

**Comment by extcode** [comment]
A quick fix for TYPO3 7.6 with PHP 7 will be replacing TYPO3\CMS\Extbase\Domain\Model\FileReference in Classes/Domain/Model/FileReference.php line 36 and 39 with \TYPO3\CMS\Core\Resource\ResourceInterface .
I'm going to refactor this in a bugfix release. This part is not needed by the Cart Extension itself. This will be used for storing invoices by the CartPdf extension.

**Comment by Hobokens** [comment]
I tried the fix in two TYPO3 7.6.10 Installations (PHP 7.0.7 and PHP 5.6). In both installations I get now the error message
`Oops, an error occurred! Code: 2016082311595363ac6360`
There are no error messages in the protocol anymore. 
Enabling the debug output in the install tool doesn't help. The error message in the frontend remains the same.

**Comment by extcode** [comment]
Did you cleared the cache after changing the model?

**Comment by Hobokens** [comment]
I cleared the cache in the install tool several times, even deleted the whole typo3temp directory.

**Comment by extcode** [comment]
I changed some code in CartPdf and remove the FileReference class. Fix version v1.1.1 the problem?

**Comment by Hobokens** [comment]
I'm sorry, still the same situation in both systems.  No error useful error messages just

`Oops, an error occurred! Code: 2016082322014613d19937`

Maybe the follwing is helpful for you. If I do not accept the 'AGB' or the 'Widerrrufsbelehrung' I get the following error:
`An error occurred while trying to call Extcode\Cart\Controller\CartController->orderCartAction()`

Thankx for your help

**Comment by extcode** [comment]
Is this site accesible or an local installation? Please contact me via my e-mail address (extension documentation). I will have a look. I will try to reproduce this error.

**Comment by BoBaH83** [comment]
if you do not check the checkboxes the validation will fail.
FE Users will see this  message:

![bildschirmfoto 2016-08-23 um 22 49 41](https://cloud.githubusercontent.com/assets/522741/17909271/08fc3dce-6984-11e6-9043-023855ff9849.png)

if you debug, you will see, this:

![bildschirmfoto 2016-08-23 um 22 46 06](https://cloud.githubusercontent.com/assets/522741/17909215/bf4c0718-6983-11e6-9e7b-c56adc79a8a4.png)

**Comment by Hobokens** [comment]
I have contacted you via e-mail.

**Comment by extcode** [comment]
The error in the screenshot is not related to the error. The error occurs when tax is zero. A fix following.

**Comment by extcode** [comment]
I released version 1.1.3.

**Comment by BoBaH83** [comment]
yes, maybe there are two issues here, I just did what @Hobokens said in [comment here](https://github.com/extcode/cart/issues/6#issuecomment-241858792) and he is right: if you do not accept terms or conditions the ugly message above appears.
It would be nice to have user friendly messages like it is on your "example" shop hoergeraete-isma.de where it says "Sie müssen den Allgemeinen Geschäftsbedingungen zustimmen." or "Sie müssen der Widerrufsbelehrung zustimmen."

**Comment by extcode** [comment]
Yes, this are two problems. The red error message above the Cart comes from:
https://github.com/extcode/cart/blob/master/Resources/Private/Templates/Cart/ShowCart.html#L4
I will have a look to have a nicer output for that with some translation.

The other messages from the example is also there:
https://github.com/extcode/cart/blob/master/Resources/Private/Partials/Cart/OrderForm/Cart.html#L21-L27
https://github.com/extcode/cart/blob/master/Resources/Private/Partials/Cart/OrderForm/Cart.html#L41-L47

**Comment by extcode** [comment]
I think the main error is fixed.
