### ISSUE TITLE
Payment provider can not use \Extcode\Cart\EventListener\Order\Finish\Email

### ISSUE THREAD

**Issue by extcode** [extcode/cart#605]
## Bug Report

**Current Behavior**
A payment provider can have its own order finish event to complete the order after a successful payment action. For certain reasons, this event can then use other EventListeners than those registered for the cart extension event. However, to avoid having to build a separate email handling for each payment provider, it would be nice if you could register the existing order finish email event listener for the order finish event of the payment provider extension. However, this leads to an error in TYPO3 v12 and v13, as the EventInterface has been replaced with concrete events. However, the EventListener only needs a class that implements the EventInterface.

**Expected behavior/output**
The EventListener can be used again.

**Environment**
- TYPO3 version(s): 12.4 and 13.4
- cart version: 9.x and 10.x

**Possible Solution**
The three EventListeners

- `\Extcode\Cart\EventListener\Order\Create\Order`
- `\Extcode\Cart\EventListener\Order\Finish\ClearCart`
- `\Extcode\Cart\EventListener\Order\Finish\Email`

should use the interface in the `__invoke()` method as in TYPO3 v11.

**Comment by rintisch** [comment]
Sorry :/
