### ISSUE TITLE
Price for 100 g

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#88]
Hi,

thanks for the great extension. I have just one question:
I want to sell wool in the shop. Normally you give the price information twice 

145 gr for 16,60 € (100 gr for 11,50 €)

What's the best way that cart calculates the price for 100 gr ?

Regards
Hobokens

**Comment by extcode** [comment]
Hi,

Cart has some BasePrice calculations included. You can define for each product in the "Measures"-tab the weight of your wool and the unit (eg. 145 and g). Then you can define the measure unit for the base price calculation. At the moment there is no possibility to add a factor to this calculation. So Cart can only calculate the base price to 1g oder 1kg. So I have to add a factor for this.
An other possible solution is to use a ViewHelper in cart/Resources/Private/Partials/Product/BasePrice.html. You can use the base price calculation of Cart to get the base price for 1g and the ViewHelper could multiply this with 100.

Regrards

Daniel

**Comment by Hobokens** [comment]
Thank you Daniel for your quick answer. You inspired me and I solved the problem this way:

TS:
```
lib.math = TEXT
  lib.math {
  current = 1
  prioriCalc = 1
}
```
And in BasePrice.html

`<cart:format.currency><f:cObject typoscriptObjectPath="lib.math" data="({product.calculatedBasePrice})*100" /></cart:format.currency>`

Regards
Hobokens

**Comment by extcode** [comment]
Sorry for closing this issue so fast. Your TypoScript solution is quite nice. Thank you for sharing this.
