### ISSUE TITLE
shipping for virtual products should be free

### ISSUE THREAD

**Issue by Scarbous** [extcode/cart#89]
My `plugin.tx_cart.shippings` config is:
<pre>
de {
	preset = 1
	options {
		1 {
			title = Standardversand
			extra = by_quantity
			extra {
				0 {
					value = 1
					extra = 2.95
				}
				1 {
					value = 5
					extra = 4.95
				}
			}
			taxClassId = 1
			status = open
			free.from = 50
			productCount {
				from = 1
				until = 5
			}
		}
	}
}
</pre>

**Comment by extcode** [comment]
This is a known issue. Thank you for reporting this. I will fix it as soon as possible in 3.x.

**Comment by extcode** [comment]
I think I wouldn't change the behaviour of the _by_quantity_. Instead I will add a new extra condition _by_number_of_physical_products_ which only counts the simple and configurable products. To allow virtual and physical goods in own product tables I will add a new isVirtualProduct and its getter and setter methods to the Cart/Product model.

**Comment by extcode** [comment]
I changed the behaviour of _by_quantity_. It's a synonym for _by_number_of_physical_products_. There are configurations for _by_number_of_virtual_products_ and _by_number_of_all_products_ if needed.

Solved with version 3.1.0.
