### ISSUE TITLE
language handling (billing.html)

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#94]
Hi,
I have configured my TYPO3 8.7.0 for one language (German) only. 
When I change the country in the template 'billing.html' some labels change the language i.e.

Versandart -> shipping method
Preis (netto) -> Price (net)
(...)

I can override the labels with TS but in my opinion the label language shoudn't change.

Regards

**Comment by extcode** [comment]
I'll try to reproduce this in the next days.

**Comment by spiegel** [comment]
Great!
Could the error depend on MySQL when it runs in strict mode?

**Comment by rintisch** [comment]
@extcode 
In my opinion this error does not occur any longer and the issue can be closed!?
